releases:
- name: dynatrace-oneagent
  version: 0.3.0

addons:
- name: dynatrace-oneagent-addon
  jobs:
  - name: dynatrace-oneagent
    release: dynatrace-oneagent
  include:
    deployments: [cf-572413dc2a9f0ef37959]
    stemcell:
      - os: ubuntu-trusty
  properties:
    dynatrace:
      environmentid: abc12345
      apitoken: bvQ0e--secret--2fEL9B
#      apiurl: https://abc12345.sprint.dynatracelabs.com/api

- name: dynatrace-oneagent-windows-addon
  jobs:
  - name: dynatrace-oneagent-windows
    release: dynatrace-oneagent
  include:
    deployments: [p-windows-runtime-8a20571b760708dcc0b9]
    stemcell:
      - os: windows2012R2
  properties:
    dynatrace:
      environmentid: abc12345
      apitoken: bvQ0e--secret--2fEL9B
#      apiurl: https://abc12345.sprint.dynatracelabs.com/api
