releases:
- name: dynatrace-oneagent
  version: 0.3.2

addons:
- name: dynatrace-oneagent-addon
  jobs:
  - name: dynatrace-oneagent
    release: dynatrace-oneagent
  include:
    stemcell:
      - os: ubuntu-trusty
  exclude:
    jobs:
    - {name: smoke-tests, release: cf}
    - {name: push-apps-manager, release: push-apps-manager-release}
    - {name: deploy-notifications, release: notifications}
    - {name: deploy-notifications-ui, release: notifications-ui}
    - {name: push-pivotal-account, release: pivotal-account}
    - {name: deploy-autoscaling, release: cf-autoscaling}
    - {name: register-broker, release: cf-autoscaling}
    - {name: nfsbrokerpush, release: nfs-volume}
    - {name: bootstrap, release: cf-mysql}
    - {name: rejoin-unsafe, release: cf-mysql}
    - {name: broker-registrar, release: cf-mysql}
    - {name: deregister-and-purge-instances, release: cf-mysql}
    - {name: smoke-tests, release: cf-mysql}
    - {name: install-hwc-buildpack, release: hwc-buildpack}
  properties:
    dynatrace:
      environmentid: abc12345
      apitoken: bvQ0e--secret--2fEL9B
      starthelper: 1

- name: dynatrace-oneagent-windows-addon
  jobs:
  - name: dynatrace-oneagent-windows
    release: dynatrace-oneagent
  include:
    stemcell:
      - os: windows2012R2
  properties:
    dynatrace:
      environmentid: abc12345
      apitoken: bvQ0e--secret--2fEL9B
