releases:
- name: dynatrace-oneagent
  version: 0.2.2

addons:
- name: dynatrace-oneagent
  jobs:
  - name: dynatrace-oneagent
    release: dynatrace-oneagent
  include:
    stemcell:
      - os: ubuntu-trusty
  properties:
    dynatrace:
      downloadurl: https://<environmentid>.live.dynatrace.com/installer/agent/unix/latest/<token>
      environmentid: abc12345
      apitoken: bvQ0e--secret--2fEL9B
