releases:
- name: dynatrace-oneagent
  version: 0.2.1

addons:
- name: dynatrace-oneagent
  jobs:
  - name: dynatrace-oneagent
    release: dynatrace-oneagent
  include:
    stemcell:
      - os: ubuntu-trusty
  properties:
    dynatrace:
      downloadurl: https://<environmentid>.live.dynatrace.com/installer/agent/unix/latest/<token>
      processhooking: 1
      proxy:
      applogaccess: 1
