---
name: dynatrace-oneagent
# local blobstore only because we don't have any blobs,
# but bosh refuses to create final releases if there is none configured
blobstore:
    provider: s3
    options:
        bucket_name: bosh-oneagent-release-blobs
